behaviors:
  PaddleBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.1
      lambd: 0.92
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 50
    max_steps: 300000000
    time_horizon: 1024
    summary_freq: 100000
    self_play:
      save_steps: 100000
      team_change: 1000000
      swap_steps: 50000
      window: 20
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
